// Day of month cannot be defined in isolation, e.g. Feb 29 is sometimes valid
// and sometimes not. See
// https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/MonthDay.html
<month_day> ::= <month> valid day of month

// Represented as https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Month.html
<month> ::= "Jan" | "Feb" | "Mar" | "Apr" | "May" | "June" | "July" | "Aug" | "Sept" | "Oct" | "Nov" | "Dec"

// Represented as https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/Year.html
<year> ::= valid year

<range> ::= <single> "-" <single>

<single> ::= <year> | <year> <month> | <year> <month_day>

// Derived dates are not always in square brackets but I need a name for this
// representation
<derived> ::= "[" <range> "]" | "[" <single> "]" | "[" <approx> "]"

<approx> ::= "?" <range> | "?" <single> | "c" <range> | "c" <single>

<undated> ::= "undated"

// I assume there can be an unbounded number of "gaps" - the only example I
// have is "1868; 1890-1902; 1933"
<gap-date> ::= <single> | <range> ";" <gap-date>

<covering-date> ::= <range> | <single> | <derived> | <appox> | <undated> | <gap-date>
