name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test-workflows:
    name: Editorial Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: sbt -v +test
      - name: Run integration tests (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sbt -v IntegrationTest/test
      - name: Run integration tests (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: unix:///Users/runner/.colima/default/docker.sock
        run: |
          brew install docker 
          brew install docker-compose
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          colima start
          echo "Pulling docker images to make the tests run quicker."
          docker-compose pull
          sbt -v IntegrationTest/test
      - name: Generate a coverage report
        run: sbt coverageReport
