name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test-workflows:
    name: Editorial Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: sbt -v +test
      - name: Run integration tests (ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sbt -v IntegrationTest/test
      # Please note that the following step will not complete; it will hang when running GetEditSetISpec.
      # See https://national-archives.atlassian.net/browse/PACT-788?focusedCommentId=42101.
      - name: Run integration tests (macos)
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: unix:///Users/runner/.colima/default/docker.sock
        run: |
          brew install docker 
          colima start
          sbt -v IntegrationTest/test
      - name: Generate a coverage report
        run: sbt coverageReport
