name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-workflows:
    name: Editorial Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: sbt -v +test
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run integration tests
        run: sbt -v IntegrationTest/test
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate a coverage report
        run: sbt coverageReport
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
