name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-workflows:
    name: Editorial Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        jdk: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run unit tests
        run: sbt -v +test
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install docker (on macos, only)
        run: brew install docker && brew install docker-compose && colima start && docker --version && earthly/earthly/earthly && earthly bootstrap
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Start docker compose
        run: docker-compose up -d && docker-compose ps
      - name: Run integration tests
        run: earthly -P --secret GITHUB_TOKEN="$GITHUB_TOKEN" +integration-test
        with:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Shutdown docker compose
        run: docker-compose down
      - name: Generate a coverage report
        run: sbt coverageReport
        with:
          GITHUB_TOKEN: ${{ github.token }}
