name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  test-workflows:
    name: Editorial Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest] Disabled as macOS job is hanging - RW 25/4/23
        jdk: [1.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Scala format
        run: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - name: Run unit tests
        run: sbt -v +test
      - name: Install docker (on macos, only)
        run: brew install docker && brew install docker-compose && colima start && docker --version
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Start docker compose
        run: docker-compose up -d && docker-compose ps
      - name: Run integration tests
        run: sbt -v IntegrationTest/test
      - name: Shutdown docker compose
        run: docker-compose down
      - name: Generate a coverage report
        run: sbt coverageReport
